### ISSUE TITLE
Interoperability with click-option-group

### ISSUE THREAD

**Issue by overclockworked64** [python-trio/asyncclick#19]
### Expected Behavior

The minimal example below should enforce any option from the required option group to be passed from the command line. 

```python
import asyncclick as click
from click_option_group import optgroup
from click_option_group import RequiredAnyOptionGroup

class PortRange(click.ParamType):
   ...

@click.command()
@click.argument('target')
@click.option('--interface', '-i', type=str, required=True)
@optgroup.group('Ports and/or port ranges', cls=RequiredAnyOptionGroup)
@optgroup.option('--port', '-p', type=click.IntRange(min=0, max=65535), multiple=True)
@optgroup.option('--range', '-r', 'range_', type=PortRange(), multiple=True)
async def main(*args, **kwargs) -> None:
    ...

if __name__ == '__main__':
    main(_anyio_backend='trio')
```

### Actual Behavior

The two libs seem to be incompatible with each other, as the traceback below suggests. However, if I replace `asyncclick` with regular `click`, it works just fine.

```pytb
❯ poetry run python -m wrath 192.168.1.1 -i enp5s0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/alex/Repositories/overclockworked64/wrath/wrath/__main__.py", line 11, in <module>
    async def main(*args, **kwargs) -> None:
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click_option_group/_decorators.py", line 137, in decorator
    func = option_group.option(*item.param_decls, **item.attrs)(func)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click_option_group/_core.py", line 174, in decorator
    func = click.option(*param_decls, group=self, **option_attrs)(func)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click_option_group/_core.py", line 31, in __init__
    super().__init__(param_decls, **attrs)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click/core.py", line 2465, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click/core.py", line 2032, in __init__
    self.type = types.convert_type(type, default)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click/types.py", line 1019, in convert_type
    return FuncParamType(ty)
  File "/home/alex/.cache/pypoetry/virtualenvs/wrath-NjAFd-T0-py3.8/lib/python3.8/site-packages/click/types.py", line 158, in __init__
    self.name = func.__name__
AttributeError: 'IntRange' object has no attribute '__name__'
```

### Environment

* Python version: 3.8.10
* Click version: 8.0.3

**Comment by smurfix** [comment]
So I async-ized the code.

asyncclick-option-group is on pypi. Tests work, dunno about actual use.
