### ISSUE TITLE
Instructions on README to set asyncclick's backend

### ISSUE THREAD

**Issue by ayharano** [python-trio/asyncclick#6]
In an asyncio project, I was testing a entry for `setup.py`'s `console_scripts`, similar to displayed in `asyncclick`'s README.rst.

However, when I ran the command of the asyncio project, the following error appeared:

```sh
> project_script
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/lib/python3.7/site-packages/anyio/__init__.py", line 57, in run
    asynclib = import_module('{}._backends._{}'.format(__name__, backend))
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/lib/python3.7/site-packages/anyio/_backends/_trio.py", line 5, in <module>
    import trio.hazmat
ModuleNotFoundError: No module named 'trio'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/bin/package_name", line 11, in <module>
    load_entry_point('package_name', 'console_scripts', 'package_name')()
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/lib/python3.7/site-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/home/user/.local/share/virtualenvs/project_root-RVI4pmxg/lib/python3.7/site-packages/anyio/__init__.py", line 59, in run
    raise LookupError('No such backend: {}'.format(backend)) from exc
LookupError: No such backend: trio
```
Reading asyncclick's `__init__.py`, I understood was to do in my file.

https://github.com/python-trio/trio-click/blob/bac4f5404749772f315b90ea38fe02de81681835/click/__init__.py#L15-L16

So in my script code I included the following lines and it worked as a charm.

```python
import asyncclick as click


# Important setting to asyncclick
click.anyio_backend = "asyncio"

...

# Actual asyncclick user code
```

Should that info be included in README.rst ?

**Comment by thiras** [comment]
This should be fixed or to be added to docs. It's not needed when run as a module but it does when you launch it from the entry point.

**Comment by smurfix** [comment]
Will fix, should inherit anyio's default.

**Comment by smurfix** [comment]
Umm, sorry about the confusion. In fact this should be long fixed by now.

**Comment by thiras** [comment]
@smurfix No, it's not or there is another problem. It works when you call it as a module but not working without `click.anyio_backend = "asyncio"` when you call it from entrypoint.

**Comment by smurfix** [comment]
Which version are you using? 7.1.2+async doesn't even *have* the string `anyio_backend`.

**Comment by smorokin** [comment]
It is in [`7.1.2`](https://github.com/python-trio/asyncclick/blob/cc1e44cc9e6e4e27a73ae48d044468ec8f704b4c/src/click/core.py#L864) and [`7.1.2.2`](https://github.com/python-trio/asyncclick/blob/9dd198d9a908647fcb3581edbf54553a208e2d9a/src/click/core.py#L864). I guess the github search is broken...
